# Generated by Django 5.0.1 on 2024-01-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="Назва статті"),
                ),
                ("content", models.TextField(verbose_name="Контент статті")),
                ("create_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Стаття",
                "verbose_name_plural": "Статті",
            },
        ),
    ]
